CHROMEOS config/docker: clean up cros-sdk Dockerfile
kernelci/kernelci-core pull request #1296
Opened 2022-07-11 14:48 UTC by gctucker

Clean up the Dockerfile for the cros-sdk image:

* sort package names alphabetically
* split long lines and long commands
* fix indentation issue with mixed tabs and spaces
* rename "user" to "cros" user

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

2022-07-12 11:43 UTC, nuclearcat commented
It will require also tiny fix in build_board.sh since username is being changed:
```
diff --git a/config/rootfs/chromiumos/scripts/build_board.sh b/config/rootfs/chromiumos/scripts/build_board.sh
index 392d968..90ba845 100755
--- a/config/rootfs/chromiumos/scripts/build_board.sh
+++ b/config/rootfs/chromiumos/scripts/build_board.sh
@@ -19,7 +19,7 @@ trap cleanup EXIT
 
 echo "Preparing environment, branch ${BRANCH}"
 sudo mkdir chromiumos-sdk
-sudo chown user chromiumos-sdk
+sudo chown ${USERNAME} chromiumos-sdk
 cd chromiumos-sdk
 git config --global user.email "bot@kernelci.org"
 git config --global user.name "KernelCI Bot"
```

2022-07-14 05:55 UTC, gctucker commented
> It will require also tiny fix in build_board.sh since username is being changed:
> 
> ```
> diff --git a/config/rootfs/chromiumos/scripts/build_board.sh b/config/rootfs/chromiumos/scripts/build_board.sh
> index 392d968..90ba845 100755
> --- a/config/rootfs/chromiumos/scripts/build_board.sh
> +++ b/config/rootfs/chromiumos/scripts/build_board.sh
> @@ -19,7 +19,7 @@ trap cleanup EXIT
>  
>  echo "Preparing environment, branch ${BRANCH}"
>  sudo mkdir chromiumos-sdk
> -sudo chown user chromiumos-sdk
> +sudo chown ${USERNAME} chromiumos-sdk
>  cd chromiumos-sdk
>  git config --global user.email "bot@kernelci.org"
>  git config --global user.name "KernelCI Bot"
> ```

Fixed in #1297

2022-07-14 06:12 UTC, nuclearcat requested changes

2022-07-14 06:19 UTC, gctucker commented on config/docker/cros-sdk/Dockerfile
> +RUN get clean \
Erm, yes. Not sure how I got that there as I'm pretty sure I built it locally.

2022-07-14 06:21 UTC, gctucker commented on config/docker/cros-sdk/Dockerfile
> +RUN get clean \
Fixed

2022-07-14 06:22 UTC, gctucker commented on config/docker/cros-sdk/Dockerfile
> +RUN chown -R cros /home/user/chromiumos
Fixed

2022-07-14 07:03 UTC, nuclearcat approved these changes

2022-07-14 10:38 UTC, merged