Merge Docker images related commits from `chromeos` branch to `main`
kernelci/kernelci-core pull request #1875
Opened 2023-04-10 14:29 UTC by mgalka

This portion of commits migrate functionality related to docker images creation and configuration from `chromeos` branch to `main` branch of kernelci-core

This should also remove the docker-old files.
Depends: #1876

2023-04-12 06:25 UTC, gctucker requested changes

2023-04-12 06:25 UTC, gctucker commented on config/docker-old/cros-baseline/Dockerfile
I don't think anything in `docker-old` should be merged in `main`, this directory needs to be deleted.

2023-04-12 08:06 UTC, mgalka commented on config/docker-old/cros-baseline/Dockerfile
I included the commits for `docker-old` just the sake of keeping history and description of some scripts which were originally added in the `docker-old` directory e.g. `tast_parser.py` or `ssh_retry.sh`. 
I was planning to add here a commit that removes `docker-old` before merging this PR (see #1876).

If we don't care about the git I can add remove `docker-old` related commits and add separate PRs to remove `docker-old` from `main` and `chromeos` branches. Do you think in such cases it's worth to modify commit messages so the information about `ssh_retry.sh` , `tast_parser.py` and possibly some others is not lost?

2023-04-12 09:36 UTC, gctucker commented on config/docker-old/cros-baseline/Dockerfile
Yes I don't think history is useful here, it would just make it harder to use with many more commits. If you know of a good reason to keep the history on the `main` branch then fine.

2023-06-19 08:22 UTC, gctucker commented
Replaced with #1964 which also removes the `docker-old` directory.

2023-06-19 08:22 UTC, closed without merging