TOML settings rework
kernelci/kernelci-core pull request #2129
Opened 2023-10-09 16:26 UTC by gctucker

Implement the TOML settings handling again in a new `kenrelci.settings` module.  This is based on the legacy one but also takes into account new features required for the `kci` command line tool as per https://github.com/kernelci/kernelci-project/discussions/261

2023-10-23 12:18 UTC, JenySadadia requested changes
Please update [kernelci.toml.sample](https://github.com/kernelci/kernelci-core/blob/main/kernelci.toml.sample) as well.

2023-10-24 07:45 UTC, nuclearcat approved these changes
LGTM, working on staging, including legacy, api, pipeline

2023-10-24 07:45 UTC, merged

2023-10-24 08:49 UTC, gctucker commented
> LGTM, working on staging, including legacy, api, pipeline

How about the sample TOML file though? @JenySadadia did you get the time to take a look?

2023-10-24 10:07 UTC, JenySadadia commented
> > LGTM, working on staging, including legacy, api, pipeline
> 
> How about the sample TOML file though? @JenySadadia did you get the time to take a look?

Yes, LGTM.