Add pyproject.toml for python packaging
kernelci/kernelci-core pull request #2286
Opened 2024-01-11 07:05 UTC by JenySadadia

Fixes https://github.com/kernelci/kernelci-core/issues/2283

With python 3.12 the support for setup.py is deprecated. Hance, update the packaging and distribution of 'kernelci' package by adding 'pyproject.toml' file.

2024-01-16 05:01 UTC, yurinnick commented
nit: If you simply moving files into `scripts` directory, `git mv` will do it better, preserving a history and keeping diff clean.

2024-01-16 05:25 UTC, JenySadadia commented
> nit: If you simply moving files into `scripts` directory, `git mv` will do it better, preserving a history and keeping diff clean.

Yes, that's true. But I didn't move them as it will affect current users and workflows as I am not sure if a specific run expects scripts to be in a specific location. @nuclearcat also flagged that maybe Jenkins workflow looks into `scripts/` directory for specific executables.

2024-01-16 05:31 UTC, yurinnick commented
I am not really opinionated about this, but it can be solved with `mv` + symlink in this case.

2024-01-16 14:11 UTC, nuclearcat commented
Small problem on staging:
```
Applying patch: patches/kernelci-core/staging.kernelci.org/0001-STAGING-add-build-configs-staging.yaml.patch
Applying patch: patches/kernelci-core/staging.kernelci.org/0002-STAGING-ensure-no-public-bisection-email-reports-are.patch
error: scripts/kci-bisect-push-results: wrong type
hint: Use 'git am --show-current-patch=diff' to see the failed patch
WARNING: Failed to apply patch
Aborting, all patches must apply.
```
adding skip label temporary to test other PR

2024-01-17 07:21 UTC, JenySadadia commented
> Small problem on staging:
> 
> ```
> Applying patch: patches/kernelci-core/staging.kernelci.org/0001-STAGING-add-build-configs-staging.yaml.patch
> Applying patch: patches/kernelci-core/staging.kernelci.org/0002-STAGING-ensure-no-public-bisection-email-reports-are.patch
> error: scripts/kci-bisect-push-results: wrong type
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> WARNING: Failed to apply patch
> Aborting, all patches must apply.
> ```
> 
> adding skip label temporary to test other PR

Thanks for reporting. I am taking a look.

2024-01-17 07:22 UTC, JenySadadia commented
Added `kernelci/script/update_sys_path.py` to enable imports from `kernelci` directory in `kci` scripts.

2024-01-17 09:53 UTC, nuclearcat commented
It still fails with same error, will add staging-skip as i'm debugging also problem with my patch on kubernetes

2024-01-17 09:53 UTC, nuclearcat commented
This is how it looks when it works:
```
Applying patch: patches/kernelci-core/staging.kernelci.org/0001-STAGING-add-build-configs-staging.yaml.patch
Applying patch: patches/kernelci-core/staging.kernelci.org/0002-STAGING-ensure-no-public-bisection-email-reports-are.patch
Applying patch: patches/kernelci-core/staging.kernelci.org/0003-STAGING-use-kernelci-staging-qemu-Docker-image.patch
Applying patch: patches/kernelci-core/staging.kernelci.org/0004-STAGING-use-staging.kernelci.org-branch-for-test-def.patch
Applying patch: patches/kernelci-core/staging.kernelci.org/0005-STAGING-use-staging-branch-for-buildroot-with-reduce.patch
Applying patch: patches/kernelci-core/staging.kernelci.org/0006-STAGING-use-staging-JWT-in-kubernetes-template.patch
```

2024-01-17 10:06 UTC, JenySadadia commented
> It still fails with same error, will add staging-skip as i'm debugging also problem with my patch on kubernetes

Yes, I haven't fixed it yet. I'm stuck with other issues in the PR.

2024-01-18 08:19 UTC, gctucker requested changes
A number of entries in the `authors` list aren't valid.  I think this is merely for users who install the package to know who is currently contributing to the code rather than a legally-binding list of contributors, which is covered by the headers in each file in the source code.  So probably it would be better to look at the top contributors or people who have contributed in the past year to manually curate this list into a more representative one.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Guillaume Tucker" , email = "guillaume.tucker@collabora.com"},
Please change to `gtucker@gtucker.io`, this address is not in use anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "kernelci.org bot" , email = "bot@kernelci.org"},
Please drop this, the bot isn't an actual author.  Maybe listing the TSC group would be useful.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Quentin Schulz" , email = "quentin.schulz@free-electrons.com"},
This one could probably be dropped, or updated with a bootlin address.  The free-electrons.com domain doesn't exist anymore (following a trademark dispute with Free ISP iirc around 2020).

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Ana Guerrero Lopez" , email = "ana.guerrero@collabora.com"},
This one can probably be dropped too, at least the email isn't valid anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "khilman" , email = "khilman@users.noreply.github.com"},
This looks like a dummy one that should be removed.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Guillaume Tucker" , email = "gtucker@gtucker.io"},
Ah I see my current email address is here so the other @collabora.com entry can just be removed.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Lakshmipathi Ganapathi" , email = "lakshmipathi.ganapathi@collabora.com"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Enric Balletbo i Serra" , email = "enric.balletbo@collabora.com"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "lakshmipathi.g" , email = "lakshmipathi.ganapathi@collabora.com"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Tomeu Vizoso" , email = "tomeu.vizoso@collabora.com"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Lakshmipathi Ganapathi" , email = "lakshmipathi.ganapathi@collabora.co.uk"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Milo Casagrande" , email = "milo@ubuntu.com"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Alex P" , email = "alexandra.pereira@collabora.com"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Guillaume Tucker" , email = "guillaume@mangoz.org"},
Ha, that's a weird one.  I don't think I've used this address in about 10 years :p  So please drop it as well.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Kevin Hilman" , email = "khilman@linaro.org"},
Probably each author should only appear once in this list.  It's not a list of email addresses but a list of people currently contributing to the code.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Lakshmipathi.G" , email = "lakshmipathi.ganapathi@collabora.com"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Milo Casagrande" , email = "milo.casagrande@linaro.org"},
Ditto - email doesn't exist anymore (foundries.io is his current address)

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "alan bennett" , email = "akbennett@hasdell"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "isaiahduncan" , email = "32970507+isaiahduncan@users.noreply.github.com"},
Dummy entry.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Alexandra" , email = "alexandra@arch.localhost"},
Dummy entry.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Alice Ferrazzi" , email = "alice.ferrazzi@cybertrust.co.jp"},
Replaced with Arisu.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Lakshmipathi.G" , email = "Lakshmipathi.Ganapathi@Collabora.com"},
Ditto - email doesn't exist anymore.

It's impressive how many email addresses Laks has used :)

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Maxime Ripard" , email = "maxime.ripard@free-electrons.com"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Mylène Josserand" , email = "mylene.josserand@collabora.com"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Nick Desaulniers" , email = "nickdesaulniers@users.noreply.github.com"},
Dummy entry.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "Thomas Petazzoni" , email = "thomas.petazzoni@free-electrons.com"},
Ditto - email doesn't exist anymore.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +  {name = "sjoerd-ccu" , email = "sjoerd.simons@collabora.co.uk"}
There's already a Sjoerd Simmons entry so this one should be dropped.

2024-01-18 08:19 UTC, gctucker commented on pyproject.toml
> +]
Arisu is listed as co-maintainer too: https://kernelci.org/docs/org/maintainers/#core-tools

2024-01-18 10:46 UTC, JenySadadia commented
> A number of entries in the `authors` list aren't valid. I think this is merely for users who install the package to know who is currently contributing to the code rather than a legally-binding list of contributors, which is covered by the headers in each file in the source code. So probably it would be better to look at the top contributors or people who have contributed in the past year to manually curate this list into a more representative one.

I have used `git shortlog --summary --email` to get all the developers and added them to this list.
Checking every file manually for the commit header would take a lot of time.

2024-01-19 12:53 UTC, JenySadadia commented
> > > > A number of entries in the `authors` list aren't valid. I think this is merely for users who install the package to know who is currently contributing to the code rather than a legally-binding list of contributors, which is covered by the headers in each file in the source code. So probably it would be better to look at the top contributors or people who have contributed in the past year to manually curate this list into a more representative one.
> > > 
> > > 
> > > I have used `git shortlog --summary --email` to get all the developers and added them to this list. Checking every file manually for the commit header would take a lot of time.
> > 
> > 
> > I don't think that's a valid approach, having this inaccurate list of contributors isn't helpful. I don't think it should take more than 15min to prepare by hand, in fact if you apply the changes from the PR review that would already be mostly done. I would suggest to not have a list of contributors at all if it's just a dump of the git history which isn't representative and contains lots of stale entries.
> 
> After taking a look at various popular Python projects, I've noticed that most of them don't specify a list of authors in `pyproject.toml`. Some have an `AUTHORS` file but that's really not required. So I think having a generic entry with the mailing list would be useful, and ensuring the list of maintainers and co-maintainers is accurate (so please add @aliceinwire to the list there as per my review comment).
> 
> It's also useful to take a look at how the legacy PyPI entry looks since this is what users will be seeing first with the v2.0 upload: https://pypi.org/project/kernelci/

Thanks for the reviews.
I have updated the list of maintainers and added Arisu to it.
About the authors, do you mean I should drop all the authors and just have `kernelci@groups.io` in the list?

2024-01-19 13:12 UTC, gctucker commented
Yes I think the list of authors should be dropped, and the new mailing list `kernelci@lists.linux.dev` should be mentioned somewhere in the meta-data but not necessarily as "authors".  One option is to just have this I guess:
```toml
authors = [
  {name = "KernelCI", email = "kernelci@lists.linux.dev"},
]
```
as I don't see any dedicated fields for a mailing list.  Django has something similar, except their have their own dedicated foundation:
https://pypi.org/project/Django/

2024-01-22 05:01 UTC, JenySadadia commented
> Yes I think the list of authors should be dropped, and the new mailing list `kernelci@lists.linux.dev` should be mentioned somewhere in the meta-data but not necessarily as "authors". One option is to just have this I guess:
> 
> ```toml
> authors = [
>   {name = "KernelCI", email = "kernelci@lists.linux.dev"},
> ]
> ```
> 
> as I don't see any dedicated fields for a mailing list. Django has something similar, except their have their own dedicated foundation: https://pypi.org/project/Django/

Okay. Thanks for the comment. Updated the authors' list.

2024-01-22 09:32 UTC, JenySadadia commented on pyproject.toml
> +kci_bisect_push_results = "kernelci.scripts.kci_bisect_push_results:main"
That's exactly why we have symlinks in the current location of the scripts e.g. `scripts/kci-bisect-push-results` 
It wasn't possible to use script names with `-` in the `project.scripts` sections. That's why I needed to rename the scripts.

2024-01-22 09:39 UTC, gctucker commented on pyproject.toml
> +kci_bisect_push_results = "kernelci.scripts.kci_bisect_push_results:main"
Ah I see, well I didn't notice the symlinks.  Still I wonder if these scripts should actually be made part of the package, but I guess there isn't a clear deprecation timeline yet.

Alright so as long as Jenkins jobs aren't broken then it should be fine.  Let's just hope that moving to symlinks doesn't have unwanted side effects.

2024-01-24 06:31 UTC, JenySadadia commented on pyproject.toml
> +kci_bisect_push_results = "kernelci.scripts.kci_bisect_push_results:main"
Tried to run Jenkins job https://bot.staging.kernelci.org/job/test-bisect/3/.
It wasn't able to kind `kci-bisect-lava-v2-callback` script. 
```
+ PYTHON_EGG_CACHE=/data/workspace/bot.staging.kernelci.org/kernel-builder/workspace/test-bisect/python-egg-cache kci-bisect-lava-v2-callback --token=**** --test-case=baseline.dmesg.emerg callback.json
/data/workspace/bot.staging.kernelci.org/kernel-builder/workspace/test-bisect__tmp/durable-171833ff/script.sh: 2: kci-bisect-lava-v2-callback: not found
```
Updated the PR to fix the issue.

2024-01-24 08:48 UTC, JenySadadia commented on pyproject.toml
> +kci_bisect_push_results = "kernelci.scripts.kci_bisect_push_results:main"
Tested OK: https://bot.staging.kernelci.org/job/test-bisect/6/

2024-01-24 09:50 UTC, nuclearcat commented
Thanks Jeny, tested on staging, and thanks for @gctucker for hint to possible point of failure and review.

2024-01-24 09:51 UTC, merged