build-configs.yaml: Build sc7180 display clock controller driver as m…
kernelci/kernelci-core pull request #2313
Opened 2024-01-22 15:19 UTC by laura-nao

…odule

Configure the display clock controller for trogdor Chromebooks to be built as a module, by modifying the arm64-chromebook fragment. This fixes a kernel hang observed on lazor and kingoftown Chromebooks when disabling the display clocks while they might still be in use.

See also: https://lore.kernel.org/linux-arm-msm/20231218091806.7155-1-laura.nao@collabora.com/

2024-01-22 16:03 UTC, laura-nao commented
Yes, I've tested the change by rerunning `baseline-nfs` with the `next-20240103` kernel revision (which previously failed - see: https://linux.kernelci.org/test/case/id/659509dbc5ec8b704377b580/) manually in LAVA: got 20/20 successful jobs without any hang (e.g. https://lava.collabora.dev/scheduler/job/12574811).

2024-03-29 16:40 UTC, a-wai commented
Added `staging-skip` to check whether this could be the cause of issues with codec tests

2024-04-03 10:29 UTC, a-wai requested changes
This seems to break codec-related Tast tests on trogdor: I couldn't find any successful job ("Complete" with at least some "pass" results) with this PR applied, while there are several passing jobs now, see https://lava.collabora.dev/results/13217203/0_tast for example.

This [patchset](https://lore.kernel.org/lkml/20240327202740.3075378-3-swboyd@chromium.org/T/) mentioned in a private chat would likely be a better fix, didn't have time to test it though.

2024-07-16 07:44 UTC, nuclearcat commented
Closing, as we are deprecating the legacy system. If this is still an issue or relevant, please re-open it under the Maestro system. Thank you for your contribution, and sorry for the inconvenience.

2024-07-16 07:44 UTC, closed without merging