rootfs-configs.yaml: Add liburing for mm selftests
kernelci/kernelci-core pull request #2340
Opened 2024-02-01 10:11 UTC by musamaanjum

The mm selftests require liburing. The binaries error out if liburing
isn't found at runtime. This will fix the following class of errors:

error while loading shared libraries: liburing.so.1: cannot open
shared object file: No such file or directory

Signed-off-by: Muhammad Usama Anjum <usama.anjum@collabora.com>

2024-02-01 10:35 UTC, obbardc requested changes

2024-02-01 10:35 UTC, obbardc commented on config/core/rootfs-configs.yaml
> +      - liburing-dev
The other library packages do not install `-dev` package (e.g. development headers).

Is it worth following exiting convention and installing the `liburing2` package directly?

2024-02-06 12:06 UTC, obbardc approved these changes

2024-02-26 14:11 UTC, nuclearcat approved these changes
kselftest images rebuilt with this PR

2024-02-26 14:12 UTC, merged