kernelci: runtime: lava: add method for retrieving device ID
kernelci/kernelci-core pull request #2519
Opened 2024-04-26 15:54 UTC by a-wai

It can be useful to know the exact device on which a job ran, without having to open the LAVA job page. Ensure this is possible by adding a new `get_device_id()` method to the `Callback` class.

2024-04-27 16:29 UTC, JenySadadia requested changes
Breaking on staging:
```
27/04/2024
21:57:43
  File "/home/kernelci/pipeline/lava_callback.py", line 84, in async_job_submit
27/04/2024
21:57:43
    device_id = job_callback.get_device_id()
27/04/2024
21:57:43
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
27/04/2024
21:57:43
AttributeError: 'Callback' object has no attribute 'get_device_id'
```
Please add `get_device_id` method to parent class constructor i.e. `Runtime`.

2024-04-29 08:26 UTC, a-wai commented
/staging

2024-04-29 09:17 UTC, a-wai commented
Moved code around to avoid possible merge conflicts with #2456

2024-04-29 09:17 UTC, a-wai commented
/staging

2024-04-29 11:32 UTC, a-wai commented
Rebased and added `get_data()` so we can save/inspect the raw callback data for debugging.

2024-04-30 08:07 UTC, a-wai commented
Tested on staging: https://staging.kernelci.org:9000/viewer?node_id=6630a4ab4d69e2d7c07dc6ba#line=24

2024-05-02 13:23 UTC, merged