kernelci/build: kselftest use .tar.xz
kernelci/kernelci-core pull request #497
Opened 2020-09-15 16:49 UTC by khilman

The LAVA test-definition has been fixed to handle .tar.xz, so
compress kselftest tarball with xz now.

Signed-off-by: Kevin Hilman <khilman@baylibre.com>

2020-09-15 16:50 UTC, khilman commented
c.f. test-definitions PR: https://github.com/Linaro/test-definitions/pull/207

Depends on https://github.com/kernelci/kernelci-core/pull/487 (probably could be cherry-picked into that PR if easier)

2020-09-17 10:30 UTC, gctucker requested changes
Found a problem with the tarball name, here's the fix: https://github.com/khilman/kernelci-core/pull/3

2020-09-17 16:26 UTC, khilman commented
> Found a problem with the tarball name, here's the fix: [khilman#3](https://github.com/khilman/kernelci-core/pull/3)

Thanks, squashed and force-pushed.

2020-09-17 19:43 UTC, gctucker approved these changes
Tested OK on staging.

2020-09-17 19:43 UTC, merged