ltp: Add ltp ipc tests using Linaro test-definitions
kernelci/kernelci-core pull request #503
Opened 2020-09-18 07:34 UTC by Lakshmipathi

Signed-off-by: Lakshmipathi <lakshmipathi.ganapathi@collabora.com>

2020-09-18 07:35 UTC, Lakshmipathi commented
Job: https://lava.collabora.co.uk/scheduler/job/2635956

2020-09-21 14:34 UTC, gctucker reviewed
Please see the comment about the test-definitions branch name, rename the test plan to 'ltp-ipc' so we can have other variants to run other parts of LTP.

2020-09-21 14:34 UTC, gctucker commented on templates/ltp/ltp.jinja2
> +         revision: master
Please use `kernelci.org` branch.

2020-09-22 17:59 UTC, Lakshmipathi commented on templates/ltp/ltp.jinja2
> +         revision: master
ok, updated the patch.

2020-09-23 08:03 UTC, gctucker requested changes
Please rename to `ltp-ipc` in `test-configs.yaml` and use the same mechanism as for v4l2-compliance and igt to define variants.  The results should appear as an `ltp-ipc` test plan, so we can run other LTP-based test plans separately but using the same `ltp.jinja2` template.

2020-09-23 08:03 UTC, gctucker commented on templates/ltp/ltp.jinja2
> +         name: ltp-ipc
This should be passed as an argument, see `v4l2-compliance` and `igt`.

2020-09-23 08:03 UTC, gctucker commented on templates/ltp/ltp.jinja2
> +    name: ltp-ipc
This should be passed as a template argument.

2020-09-24 17:36 UTC, Lakshmipathi commented
LAVA job with updated changes: https://lava.collabora.co.uk/scheduler/job/2653221

2020-09-24 21:38 UTC, gctucker commented
@Lakshmipathi Thanks - can you please rebase this PR? It appears to be conflicting now.

2020-09-28 05:52 UTC, Lakshmipathi commented
ok, now the patch rebased on master.

2020-09-28 12:12 UTC, gctucker commented
Great, first results can now be seen on staging:
https://staging.kernelci.org/test/plan/id/5f719d53813243286aa69d3c/

2020-09-28 12:15 UTC, gctucker approved these changes

2020-10-02 09:32 UTC, merged