update build directory in kubernetes template
kernelci/kernelci-core pull request #528
Opened 2020-11-03 22:39 UTC by alexandrasp

Many selftests are looking for libraries in kernel directory, so it changes output of build_kernel to kernel dir as default.

Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

2020-11-03 22:47 UTC, gctucker commented
I think you meant "header files" rather than "libraries" in the commit message?

Also please wrap long lines in the commit message as it's otherwise it gets hard to read in most Git tools.

2020-11-03 22:53 UTC, alexandrasp commented
> I think you meant "header files" rather than "libraries" in the commit message?
> 
> Also please wrap long lines in the commit message as it's otherwise it gets hard to read in most Git tools.

updated

2020-11-04 13:59 UTC, gctucker requested changes
This seems to be breaking all the kernel builds on staging, at least the install and publish steps:
```
+ ./kci_build install_kernel --kdir /scratch/linux --output /root/build --build-config kernelci_staging-stable --describe=staging-stable-20201104.0 --describe-verbose=v5.4-9334-g480bde10cfc2 --commit=480bde10cfc24ad8002f0deca42ba380416dafe4
Traceback (most recent call last):
  File "./kci_build", line 353, in <module>
    status = opts.command(configs, opts)
  File "./kci_build", line 306, in __call__
    args.install_path, args.mod_path)
  File "/scratch/kernelci-core/kernelci/build.py", line 763, in install_kernel
    with open(os.path.join(output_path, 'bmeta.json')) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/build/bmeta.json'
```

2020-11-04 21:01 UTC, alexandrasp commented
> This seems to be breaking all the kernel builds on staging, at least the install and publish steps:
> 
> ```
> + ./kci_build install_kernel --kdir /scratch/linux --output /root/build --build-config kernelci_staging-stable --describe=staging-stable-20201104.0 --describe-verbose=v5.4-9334-g480bde10cfc2 --commit=480bde10cfc24ad8002f0deca42ba380416dafe4
> Traceback (most recent call last):
>   File "./kci_build", line 353, in <module>
>     status = opts.command(configs, opts)
>   File "./kci_build", line 306, in __call__
>     args.install_path, args.mod_path)
>   File "/scratch/kernelci-core/kernelci/build.py", line 763, in install_kernel
>     with open(os.path.join(output_path, 'bmeta.json')) as json_file:
> FileNotFoundError: [Errno 2] No such file or directory: '/root/build/bmeta.json'
> ```

@gctucker I pushed an option to fix it. It seems to be ok to remove `OUTPUT` variable. Now kernel building and installation will be into linux directory.

2020-11-06 00:00 UTC, alexandrasp commented
Full log with this PR applied:
https://storage.staging.kernelci.org/kernelci/staging-mainline/staging-mainline-20201105.2/arm64/defconfig+kselftest/gcc-8/build.log

Errors related to `#include <fuse.h>` and  `#include <numa.h>` have gone. It was necessary to install both libraries because are from user-space.

2020-11-09 17:56 UTC, alexandrasp commented
Now that libraries from kernel have been installed as expected by selftests into kernel directory all build errors related to includes has gone.(e.g. `#include <drm/drm.h>`, `#include <linux/udmabuf.h>`, `#include <linux/android/binderfs.h>`, etc)

[ARM64 logs](https://storage.staging.kernelci.org/kernelci/staging-mainline/staging-mainline-20201109.0/arm64/defconfig+kselftest/gcc-8/build.log)
[ARM logs](https://storage.staging.kernelci.org/kernelci/staging-mainline/staging-mainline-20201109.0/arm/multi_v7_defconfig+kselftest/gcc-8/build.log)
[x86_64 logs](https://storage.staging.kernelci.org/kernelci/staging-mainline/staging-mainline-20201109.0/x86_64/x86_64_defconfig+kselftest/gcc-8/build.log)

2020-11-09 21:11 UTC, gctucker approved these changes
Thanks, tested OK with no regressions on staging.

2020-11-09 21:11 UTC, merged