kci_doc: Fix buster-btrfs build documentation
kernelci/kernelci-core pull request #546
Opened 2020-11-19 09:29 UTC by mgalka

This commit fixes build instructions for buster-btrfs rootfs. Moves
build time dependencies to the build script and cleans up some
unnecessary files.

Signed-off-by: Michal Galka <michal.galka@collabora.com>

2020-11-19 09:35 UTC, gctucker requested changes

2020-11-19 09:35 UTC, gctucker commented on doc/kci_testsuite.md
> +  buster-btrfs:
Well, please clean up.

2020-11-19 10:19 UTC, mgalka commented on doc/kci_testsuite.md
> +  buster-btrfs:
Done

2020-11-19 13:52 UTC, gctucker commented on doc/kci_testsuite.md
> +apt-get update -y && apt-get install -y $BUILD_DEPS
```suggestion
apt-get update && apt-get install -y $BUILD_DEPS
```

2020-11-19 13:52 UTC, gctucker commented on doc/kci_testsuite.md
> +./autogen.sh && ./configure --disable-documentation
Maybe add `set -e` at the top of the script and drop the `&&` to put only one command on each line.

2020-11-24 13:50 UTC, gctucker reviewed
Thanks, looks good.  Only thing is that `kci_doc` in the commit subject looks like a command line tool like `kci_build` but it's not.  I see a previous commit from @Lakshmipathi also did something like that, but `doc:` would be better.

2020-11-24 17:24 UTC, mgalka commented
> Thanks, looks good. Only thing is that `kci_doc` in the commit subject looks like a command line tool like `kci_build` but it's not. I see a previous commit from @Lakshmipathi also did something like that, but `doc:` would be better.

That's exactly why I started the commit message with `kci_doc`. Changed it to `doc`.

2020-11-25 08:51 UTC, gctucker approved these changes

2020-11-25 08:51 UTC, merged