test-configs.yaml: enable jacuzzi in kernelCI
kernelci/kernelci-core pull request #761
Opened 2021-07-15 17:40 UTC by alexandrasp

Enable acer-mt8183-cp311-3h-jacuzzi device type in kernelCI and include baseline and kselftest test plans to it.

Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

2021-07-19 11:14 UTC, gctucker commented
LGTM, we now need to get some results on staging to confirm.

2021-07-20 06:05 UTC, gctucker commented
There aren't any results yet for jacuzzi, no jobs were submitted in LAVA.  It seems worth checking what the issue is, maybe the device tree name doesn't match the LAVA device type name.

I think it's implicit that the changes are for KernelCI, so it doesn't really need to be in the commit message.  If you want to mention it, there should be a capital K to be consistent with the logo and "branding".

2021-07-20 06:09 UTC, gctucker commented
Looks like there's a problem with the LAVA device type indeed, here's the list of jacuzzi dtb variants in today's next:
```
gtucker@submarine:~/src/linux [(HEAD detached at next-20210720)]
$ find arch/arm64/boot/dts/mediatek/*jacu*
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-burnet.dts
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-damu.dts
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi.dtsi
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-fennel14.dts
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-fennel.dtsi
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-fennel-sku1.dts
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-fennel-sku6.dts
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-juniper.dtsi
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-juniper-sku16.dts
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-kappa.dts
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-kenzo.dts
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-willow.dtsi
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-willow-sku0.dts
arch/arm64/boot/dts/mediatek/mt8183-kukui-jacuzzi-willow-sku1.dts
```

2021-07-20 08:07 UTC, gctucker commented
As discussed with @eballetbo, the device tree for this Chromebook is `mt8183-kukui-jacuzzi-juniper-sku16`.  So the LAVA device type name should be changed accordingly, to follow the convention used with other DT devices.

2021-07-20 08:30 UTC, gctucker commented
Thanks @MyleneJ for the upstream fix in LAVA https://git.lavasoftware.org/lava/lava/-/merge_requests/1546

2021-07-20 12:42 UTC, alexandrasp commented
@gctucker yesterday I noticed it during my night because I checked dtb files, thanks for checking it with @eballetbo and @MyleneJ before the beginning of my day.

2021-07-20 14:28 UTC, Lakshmipathi commented
changes LGTM

2021-07-20 15:39 UTC, gctucker commented
> changes LGTM

Aside from the fact that the device type name needs to be changed to match the device tree name, as discussed in previous comments ;)

2021-07-21 19:06 UTC, gctucker requested changes
The list of test plans matches the docs on https://static.staging.kernelci.org/docs/tests/

The name of the device type needs to be changed to match the device tree name.

2021-07-21 19:06 UTC, gctucker commented on config/core/test-configs.yaml
> +  acer-mt8183-cp311-3h-jacuzzi:
```suggestion
  mt8183-kukui-jacuzzi-juniper-sku16:
```
As discussed on this PR.

2021-07-22 02:03 UTC, alexandrasp commented on config/core/test-configs.yaml
> +  acer-mt8183-cp311-3h-jacuzzi:
updated

2021-07-22 06:16 UTC, gctucker commented
OK, now waiting for the new device type to be set up in lab-collabora to get some results on staging.

2021-07-22 06:16 UTC, gctucker approved these changes

2021-07-22 06:19 UTC, gctucker commented
@alexandrasp Also please see my earlier comment:

> I think it's implicit that the changes are for KernelCI, so it doesn't really need to be in the commit message. If you want to mention it, there should be a capital K to be consistent with the logo and "branding".

2021-07-26 10:32 UTC, gctucker commented
@alexandrasp Please update the commit message with the new device type name:

> Enable acer-mt8183-cp311-3h-jacuzzi device type

Other than that, the changes look good now.  We just need to wait until the device type name becomes available in lab-collabora to get some results on staging.

2021-07-26 12:09 UTC, alexandrasp commented
> @alexandrasp Please update the commit message with the new device type name:
> 
> > Enable acer-mt8183-cp311-3h-jacuzzi device type
> 
> Other than that, the changes look good now. We just need to wait until the device type name becomes available in lab-collabora to get some results on staging.

ok, it sounds good! I saw that Mylene's PR to rename is still open.

2021-07-26 18:50 UTC, gctucker commented
I've added an alias in Collabora's LAVA lab to be able to start the correct name until the change is merged upstream and the lab gets updated.

2021-07-29 13:25 UTC, alexandrasp commented on config/core/test-configs.yaml
> +      - baseline
tested OK on staging: https://staging.kernelci.org/test/plan/id/610036d80528960161d74f55/

2021-07-29 13:26 UTC, alexandrasp commented on config/core/test-configs.yaml
> +      - baseline-nfs
tested OK on staging: https://staging.kernelci.org/test/plan/id/610037199fa03065ebd74f93/

2021-07-30 03:32 UTC, alexandrasp commented on config/core/test-configs.yaml
> +      - kselftest-filesystems
tested OK on staging: https://staging.kernelci.org/test/plan/id/6102dc8abafc6a321dd74f58/

2021-07-30 03:32 UTC, alexandrasp commented on config/core/test-configs.yaml
> +      - kselftest-futex
tested OK on staging: https://staging.kernelci.org/test/plan/id/6102dbad24492cd97cd74f4a/

2021-07-30 03:33 UTC, alexandrasp commented on config/core/test-configs.yaml
> +      - kselftest-lib
tested OK on staging: https://staging.kernelci.org/test/plan/id/6102dcfc77db0fffafd74f5a/

2021-07-30 03:34 UTC, alexandrasp commented on config/core/test-configs.yaml
> +      - kselftest-lkdtm
tested OK on staging: https://staging.kernelci.org/test/plan/id/6102dc3ab6161806cbd74fd0/

2021-07-30 03:35 UTC, alexandrasp commented on config/core/test-configs.yaml
> +      - kselftest-seccomp
tested OK on staging: https://staging.kernelci.org/test/plan/id/6102dc5d81accdebc9d74f72/

2021-07-30 06:03 UTC, gctucker commented
@alexandrasp I still see the initial device type name in the commit message:

> Enable acer-mt8183-cp311-3h-jacuzzi device type and include baseline and kselftest test plans.

It should be `mt8183-kukui-jacuzzi-juniper-sku16`.

2021-07-30 12:05 UTC, alexandrasp commented
> @alexandrasp I still see the initial device type name in the commit message:
> 
> > Enable acer-mt8183-cp311-3h-jacuzzi device type and include baseline and kselftest test plans.
> 
> It should be `mt8183-kukui-jacuzzi-juniper-sku16`.

thanks @gctucker, updated.

2021-07-30 15:16 UTC, merged

2021-07-30 15:38 UTC, gctucker commented
Device type name updated upstream in LAVA: https://git.lavasoftware.org/lava/lava/-/merge_requests/1546