test-configs: Use implementation defined FEAT_PAUTH with qemu on arm64
kernelci/kernelci-core pull request #921
Opened 2021-12-01 20:54 UTC by broonie

The implementation of the architected pointer authentication implementation
in qemu is very slow so qemu provides optional support for an additional
implementation defined algorithm which runs much faster. This is not so
noticeable when userspace doesn't make use of pointer authentication but
once it does the performance improvement is dramatic. Switch our virtual
arm64 targets over to this, there's no real coverage impact for the kernel.

Signed-off-by: Mark Brown <broonie@kernel.org>

2021-12-13 21:54 UTC, gctucker requested changes
This appears to be causing a lot of breakage on staging:
https://staging.kernelci.org/test/job/next/branch/master/kernel/v5.16-rc4-6579-gea922272cbe5/plan/baseline/

For example, on `qemu_arm64-virt-gicv2`:
https://storage.staging.kernelci.org/next/master/v5.16-rc4-6579-gea922272cbe5/arm64/defconfig/clang-11/lab-baylibre/baseline-qemu_arm64-virt-gicv2.html
```
06:49:59.314434  qemu-system-aarch64: can't apply global max-arm-cpu.pauth-impdef=on: Property '.pauth-impdef' not found
```
Does this option require a particular version of QEMU?

2022-02-03 13:13 UTC, broonie commented
Given that we're going to be switching to running qemu jobs in docker with KernelCI's qemu there shouldn't be any blocker to enabling this.

2022-02-04 14:12 UTC, gctucker commented
Except the QEMU version currently in the KernelCI docker images (default from Debian Bullseye) doesn't seem to support this feature:
https://staging.kernelci.org/test/case/id/61fc75b8d32f2cd72ac2fcc4/
https://storage.staging.kernelci.org/kernelci/staging-mainline/staging-mainline-20220204.0/arm64/defconfig/gcc-10/lab-baylibre/baseline-qemu_arm64-virt-gicv2.html#L181
```
qemu-system-aarch64: can't apply global max-arm-cpu.pauth-impdef=on: Property 'max-arm-cpu.pauth-impdef' not found
```
This is the version from Bullseye:
```
$ apt policy qemu-system-arm
qemu-system-arm:
  Installed: 1:5.2+dfsg-11+deb11u1
  Candidate: 1:5.2+dfsg-11+deb11u1
  Version table:
 *** 1:5.2+dfsg-11+deb11u1 500
        500 https://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```
Which QEMU version is required for pointer authentication?

2022-02-04 14:13 UTC, gctucker approved these changes

2022-02-09 17:59 UTC, gctucker commented
Adding `staging-skip` label to get passing QEMU jobs so we can test and merge #1015 to switch to Docker.

2022-02-16 16:11 UTC, gctucker commented
OK the PR to switch to only run QEMU jobs in Docker has been merged so removing the skip label now.

2022-03-16 07:06 UTC, gctucker commented
Here's a mainline job with arm64 GIC v3 running fine in production with the `kernelci/qemu` Docker image
https://linux.kernelci.org/test/plan/id/622a4d0e20fe38ddb8c62993/
```
  171 19:08:36.432205  Boot command: docker run --rm --init --interactive --tty --device=/dev/kvm --mount=type=bind,source=/var/lib/lava/dispatcher/tmp,destination=/var/lib/lava/dispatcher/tmp kernelci/qemu qemu-system-aarch64 -cpu max -machine virt,gic-version=3,mte=on,accel=kvm:tcg -nographic -net nic,model=virtio,macaddr=52:54:00:12:34:58 -net user -m 512 -monitor none -kernel /var/lib/lava/dispatcher/tmp/1676382/deployimages-ewkbgsm6/kernel/Image -append "console=ttyAMA0,115200 root=/dev/ram0 debug verbose console_msg_format=syslog earlycon" -initrd /var/lib/lava/dispatcher/tmp/1676382/deployimages-ewkbgsm6/ramdisk/rootfs.cpio.gz -drive format=qcow2,file=/var/lib/lava/dispatcher/tmp/1676382/apply-overlay-guest-__hf_y9j/lava-guest.qcow2,media=disk,if=virtio,id=lavatest
[...]
  179 19:08:39.380626  qemu-system-aarch64: invalid accelerator kvm
  180 19:08:39.382210  qemu-system-aarch64: falling back to tcg
  181 19:08:39.750918  [    0.000000] Booting Linux on physical CPU 0x0000000000 [0x000f0510]
  190 19:08:39.755861  [    0.000000] Linux version 5.17.0-rc7 (KernelCI@build-j603213-arm64-gcc-10-defconfig-df4tt) (aarch64-linux-gnu-gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PREEMPT Thu Mar 10 18:51:53 UTC 2022
  191 19:08:39.756130  [    0.000000] Machine model: linux,dummy-virt
```

The same job in the same lab with mainline on staging, with the changes from this PR and the `kernelci/staging-qemu` Docker image which should be the same:
https://staging.kernelci.org/test/case/id/62305665da14686c104b31a1/
```
  171 09:03:13.912155  Boot command: docker run --rm --init --interactive --tty --device=/dev/kvm --mount=type=bind,source=/var/lib/lava/dispatcher/tmp,destination=/var/lib/lava/dispatcher/tmp kernelci/staging-qemu qemu-system-aarch64 -cpu max,pauth-impdef=on -machine virt,gic-version=3,mte=on,accel=kvm:tcg -nographic -net nic,model=virtio,macaddr=52:54:00:12:34:58 -net user -m 512 -monitor none -kernel /var/lib/lava/dispatcher/tmp/1698872/deployimages-bj3lfti0/kernel/Image -append "console=ttyAMA0,115200 root=/dev/ram0 debug verbose console_msg_format=syslog earlycon" -initrd /var/lib/lava/dispatcher/tmp/1698872/deployimages-bj3lfti0/ramdisk/rootfs.cpio.gz -drive format=qcow2,file=/var/lib/lava/dispatcher/tmp/1698872/apply-overlay-guest-qxqtxomj/lava-guest.qcow2,media=disk,if=virtio,id=lavatest
[...]
  179 09:03:21.104659  qemu-system-aarch64: invalid accelerator kvm
  180 09:03:21.106334  qemu-system-aarch64: falling back to tcg
  181 09:03:21.108115  qemu-system-aarch64: can't apply global max-arm-cpu.pauth-impdef=on: Property 'max-arm-cpu.pauth-impdef' not found
```
There is no difference in the `kernelci/qemu` Dockerfile between production and staging:
```
$ git diff --stat prod/main prod/staging.kernelci.org config/docker 
 config/docker/gcc-10_x86/Dockerfile           |   4 ++
 config/docker/gcc-10_x86/gcc-header-fix.patch | 154 +++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 158 insertions(+)
```

So back to last month's [question](https://github.com/kernelci/kernelci-core/pull/921#issuecomment-1030025691), do you know which version of QEMU is required to support `max-arm-cpu.pauth-impdef`?

2022-04-16 14:25 UTC, broonie commented
It's been there since 6.0 - https://wiki.qemu.org/ChangeLog/6.0#Arm

2022-04-16 14:28 UTC, broonie commented
We also shouldn't be trying to use the KVM accelerator here since that will limit us to the host CPU's feature set if the test runs on the same CPU architecture as the target, that would be a separate test for virtualisation.

2022-04-18 11:58 UTC, gctucker commented
Great, so hopefully this will get resolved with #1131.

2022-04-18 19:23 UTC, gctucker approved these changes
Tested OK on staging:
https://storage.staging.kernelci.org/kernelci/staging-mainline/staging-mainline-20220418.0/arm64/defconfig+arm64-chromebook/gcc-10/lab-baylibre/baseline-qemu_arm64-virt-gicv2.html#L184
```
cpu max,pauth-impdef=on 
```

https://staging.kernelci.org/test/plan/id/625d27f280e2f7d1d505f4d9/

2022-04-18 19:24 UTC, merged